export const LEADS = [
  { id:'L-001', name:'Marcus Webb',      company:'Webb Contracting LLC',    segment:'Commercial',  state:'FL', status:'Enriched', email:'m.webb@webbcontracting.com',    phone:'(561) 449-2210', source:'Apollo',     createdAt:'2025-01-14', score:82, employees:'11–50',   revenue:'$2.4M',  website:'webbcontracting.com',    linkedin:'/in/marcuswebb',    notes:'Interested in CRM integration.' },
  { id:'L-002', name:'Patricia Nguyen',  company:'Nguyen & Associates',     segment:'Government',  state:'VA', status:'Enriched', email:'pnguyen@nassociates.gov',       phone:'(703) 881-0044', source:'Manual',     createdAt:'2025-01-13', score:91, employees:'51–200',  revenue:'$8.1M',  website:'nassociates.gov',        linkedin:'/in/pnguyen',       notes:'DoD subcontractor. High priority.' },
  { id:'L-003', name:'Derek Okafor',     company:'Okafor Capital',          segment:'Commercial',  state:'NY', status:'Pending',  email:'d.okafor@okaforcap.com',        phone:'(212) 555-0183', source:'LinkedIn',   createdAt:'2025-01-12', score:67, employees:'1–10',    revenue:'$1.1M',  website:'okaforcap.com',          linkedin:'/in/derekokafor',   notes:'' },
  { id:'L-004', name:'Sandra Kim',       company:'Kim Home Group',          segment:'Residential', state:'FL', status:'Enriched', email:'sandra@kimhomegroup.com',       phone:'(561) 772-3390', source:'Apollo',     createdAt:'2025-01-11', score:74, employees:'1–10',    revenue:'$600K',  website:'kimhomegroup.com',       linkedin:'/in/sandrakim',     notes:'' },
  { id:'L-005', name:'Gerald Thompson',  company:'GTech Solutions',         segment:'Commercial',  state:'TX', status:'Raw',      email:'g.thompson@gtech.io',           phone:'(214) 887-2210', source:'Web Scrape', createdAt:'2025-01-10', score:45, employees:'11–50',   revenue:'$3.7M',  website:'gtech.io',               linkedin:'/in/geraldthompson', notes:'Needs manual verification.' },
  { id:'L-006', name:'Aisha Patel',      company:'Patel Defense Group',     segment:'Government',  state:'MD', status:'Enriched', email:'apatel@pateldefense.com',       phone:'(301) 445-7721', source:'Referral',   createdAt:'2025-01-09', score:88, employees:'51–200',  revenue:'$15.2M', website:'pateldefense.com',       linkedin:'/in/aishapatel',    notes:'Strong referral from existing client.' },
  { id:'L-007', name:'Carlos Mendez',    company:'Mendez Properties',       segment:'Residential', state:'FL', status:'Pending',  email:'carlos@mendezprops.com',        phone:'(305) 990-1147', source:'Apollo',     createdAt:'2025-01-08', score:59, employees:'1–10',    revenue:'$420K',  website:'mendezprops.com',        linkedin:'/in/carlosmendez',  notes:'' },
  { id:'L-008', name:'Brenda Wallace',   company:'Wallace Analytics',       segment:'Commercial',  state:'CA', status:'Failed',   email:'brenda@wallaceanalytics.ai',    phone:'(415) 500-3348', source:'LinkedIn',   createdAt:'2025-01-07', score:0,  employees:'11–50',   revenue:'$5.0M',  website:'wallaceanalytics.ai',    linkedin:'/in/brendawallace', notes:'Email bounce. Needs updated contact.' },
  { id:'L-009', name:'James Okello',     company:'Okello Systems',          segment:'Government',  state:'VA', status:'Enriched', email:'j.okello@okello.gov',           phone:'(571) 334-9901', source:'Manual',     createdAt:'2025-01-06', score:79, employees:'201–500', revenue:'$22M',   website:'okello.gov',             linkedin:'/in/jamesokello',   notes:'DARPA-adjacent programs.' },
  { id:'L-010', name:'Tanya Reeves',     company:'Reeves Marketing Group',  segment:'Commercial',  state:'GA', status:'Raw',      email:'treeves@reedmktg.com',          phone:'(404) 221-8890', source:'Web Scrape', createdAt:'2025-01-05', score:38, employees:'1–10',    revenue:'$780K',  website:'reedmktg.com',           linkedin:'/in/tanyareeves',   notes:'' },
  { id:'L-011', name:'Kevin Larson',     company:'Larson Industrial',       segment:'Commercial',  state:'IL', status:'Enriched', email:'k.larson@larsonindustrial.com', phone:'(312) 445-0012', source:'Apollo',     createdAt:'2025-01-04', score:85, employees:'201–500', revenue:'$40M',   website:'larsonindustrial.com',   linkedin:'/in/kevinlarson',   notes:'Ops automation strong fit.' },
  { id:'L-012', name:'Monique Foster',   company:'Foster Health Tech',      segment:'Commercial',  state:'CO', status:'Pending',  email:'m.foster@fosterhealthtech.com', phone:'(720) 833-5541', source:'LinkedIn',   createdAt:'2025-01-03', score:62, employees:'11–50',   revenue:'$3.2M',  website:'fosterhealthtech.com',   linkedin:'/in/moniquefoster', notes:'HealthTech, lower priority segment.' },
  { id:'L-013', name:'Devon Harris',     company:'Harris Defense Systems',  segment:'Government',  state:'VA', status:'Enriched', email:'d.harris@harrisdefense.com',    phone:'(571) 229-4441', source:'Referral',   createdAt:'2025-01-02', score:94, employees:'51–200',  revenue:'$18M',   website:'harrisdefense.com',      linkedin:'/in/devonharris',   notes:'Top priority. Cleared facility.' },
  { id:'L-014', name:'Priya Sharma',     company:'Sharma Consulting',       segment:'Commercial',  state:'TX', status:'Enriched', email:'priya@sharmaconsult.co',        phone:'(214) 660-3309', source:'Apollo',     createdAt:'2025-01-01', score:71, employees:'1–10',    revenue:'$1.8M',  website:'sharmaconsult.co',       linkedin:'/in/priyasharma',   notes:'' },
];

export const ACTIVITY = [
  { id:1, event:'Pipeline run completed — 12 leads enriched',                    time:'2 hours ago',  color:'#2d6a4f' },
  { id:2, event:'New lead added: Brenda Wallace (Wallace Analytics)',             time:'4 hours ago',  color:'#1e40af' },
  { id:3, event:'Export generated — 47 Government leads exported to CSV',         time:'6 hours ago',  color:'#92400e' },
  { id:4, event:'Lead updated: Patricia Nguyen — status set to Enriched',         time:'8 hours ago',  color:'#1e40af' },
  { id:5, event:'Pipeline scheduled — cron 0 6 * * *',                           time:'1 day ago',    color:'#2d6a4f' },
  { id:6, event:'Apollo API key refreshed successfully',                          time:'2 days ago',   color:'#909090' },
  { id:7, event:'3 leads marked as Failed — email bounce detected',               time:'2 days ago',   color:'#b91c1c' },
  { id:8, event:'Export generated — full leads database (CSV, 14 records)',       time:'3 days ago',   color:'#92400e' },
];
