#!/bin/bash
# Firebase Setup Script for MDO3D Apps
# Updates HTML files and creates firebase.js configs

set -e

# Firebase configs for each domain
CAREER_CONFIG='const FIREBASE_CONFIG = {
  apiKey: "AIzaSyDCIDNUzirzlHapKBLcMXR-iYSOiV6yUvo",
  authDomain: "mdo3d-career.firebaseapp.com",
  projectId: "mdo3d-career",
  storageBucket: "mdo3d-career.firebasestorage.app",
  messagingSenderId: "408387980482",
  appId: "1:408387980482:web:d564e195308f4da2553f5b"
};'

UTILITIES_CONFIG='const FIREBASE_CONFIG = {
  apiKey: "AIzaSyBkNK59CoXyS9qn65c2mbWiBVT_KUOgul4",
  authDomain: "mdo3d-utilities.firebaseapp.com",
  projectId: "mdo3d-utilities",
  storageBucket: "mdo3d-utilities.firebasestorage.app",
  messagingSenderId: "699798570384",
  appId: "1:699798570384:web:aa658f6732f1db10e31f15"
};'

LEADS_CONFIG='const FIREBASE_CONFIG = {
  apiKey: "AIzaSyBiiwVaxvzcGb7Vgpk2m_H-KMm0ZB8nJIU",
  authDomain: "mdo3d-leads.firebaseapp.com",
  projectId: "mdo3d-leads",
  storageBucket: "mdo3d-leads.firebasestorage.app",
  messagingSenderId: "862220604451",
  appId: "1:862220604451:web:cd2eb7605238e19ba10d96"
};'

FIREBASE_SDK='    <!-- Firebase SDK -->
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js"></script>
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-auth-compat.js"></script>
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore-compat.js"></script>
'

# Function to create firebase.js
create_firebase_js() {
    local dir="$1"
    local app_name="$2"
    local config="$3"

    mkdir -p "$dir/js/config"

    cat > "$dir/js/config/firebase.js" << FIREBASE_EOF
/**
 * Firebase Configuration for ${app_name}
 * Auto-generated by setup-firebase.sh
 */

${config}

const APP_NAME = '${app_name}';

class FirebaseService {
  constructor() {
    this.config = FIREBASE_CONFIG;
    this.app = null;
    this.auth = null;
    this.db = null;
    this.initialized = false;
  }

  async initialize() {
    if (this.initialized) return true;
    if (typeof firebase === 'undefined') {
      console.warn('[Firebase] SDK not loaded.');
      return false;
    }

    try {
      this.app = firebase.apps.length === 0 ? firebase.initializeApp(this.config) : firebase.apps[0];
      this.auth = firebase.auth();
      this.db = firebase.firestore();
      this.initialized = true;
      await this.signInAnonymously();
      console.log('[Firebase] Initialized successfully');
      return true;
    } catch (error) {
      console.error('[Firebase] Initialization error:', error);
      return false;
    }
  }

  async signInAnonymously() {
    if (!this.auth) return null;
    try {
      if (this.auth.currentUser) return this.auth.currentUser;
      const result = await this.auth.signInAnonymously();
      return result.user;
    } catch (error) {
      console.warn('[Firebase] Anonymous sign-in failed:', error.message);
      return null;
    }
  }

  getAuth() { return this.auth; }
  getFirestore() { return this.db; }
  getCurrentUser() { return this.auth?.currentUser || null; }

  async saveDocument(data) {
    if (!this.db || !this.auth?.currentUser) return null;
    try {
      const ref = await this.db.collection(APP_NAME + '_documents').add({
        uid: this.auth.currentUser.uid,
        timestamp: firebase.firestore.FieldValue.serverTimestamp(),
        ...data
      });
      return ref.id;
    } catch (error) {
      console.warn('[Firebase] saveDocument failed:', error.message);
      return null;
    }
  }

  async getDocumentHistory(maxItems = 20) {
    if (!this.db || !this.auth?.currentUser) return [];
    try {
      const snapshot = await this.db.collection(APP_NAME + '_documents')
        .where('uid', '==', this.auth.currentUser.uid)
        .orderBy('timestamp', 'desc')
        .limit(maxItems)
        .get();
      return snapshot.docs.map(function(doc) { return { id: doc.id, ...doc.data() }; });
    } catch (error) {
      console.warn('[Firebase] getDocumentHistory failed:', error.message);
      return [];
    }
  }

  async getPremiumStatus() {
    if (!this.db || !this.auth?.currentUser) return { isPremium: false };
    try {
      var doc = await this.db.collection('users').doc(this.auth.currentUser.uid).get();
      return doc.exists ? doc.data() : { isPremium: false };
    } catch (error) {
      return { isPremium: false };
    }
  }
}

export const firebaseConfig = new FirebaseService();
FIREBASE_EOF

    echo "  Created: $dir/js/config/firebase.js"
}

# Function to add Firebase SDK to HTML
add_firebase_sdk() {
    local html_file="$1"

    # Check if already has Firebase SDK
    if grep -q "firebase-app-compat" "$html_file" 2>/dev/null; then
        echo "  Skipped (already has SDK): $html_file"
        return
    fi

    # Try different script tag patterns
    if grep -q '<script.*src="js/app.js"' "$html_file"; then
        sed -i '' 's|<script.*src="js/app.js".*</script>|<!-- Firebase SDK -->\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js"></script>\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-auth-compat.js"></script>\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore-compat.js"></script>\
\
    <script src="js/app.js" type="module"></script>|' "$html_file"
        echo "  Updated: $html_file"
    elif grep -q '</body>' "$html_file"; then
        sed -i '' 's|</body>|<!-- Firebase SDK -->\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-app-compat.js"></script>\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-auth-compat.js"></script>\
    <script src="https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore-compat.js"></script>\
</body>|' "$html_file"
        echo "  Updated: $html_file"
    else
        echo "  WARNING: Could not update $html_file"
    fi
}

echo "=== Setting up Career Apps (rigor) ==="
for html in /Users/latarencebutts/mdo3d/projects/rigor/*/public/index.html; do
    if [ -f "$html" ]; then
        dir=$(dirname "$html")
        app_name=$(basename "$(dirname "$dir")")
        add_firebase_sdk "$html"
        create_firebase_js "$dir" "$app_name" "$CAREER_CONFIG"
    fi
done

echo ""
echo "=== Setting up Utility Apps (mdothree) ==="
for html in /Users/latarencebutts/mdo3d/projects/mdothree/*/public/index.html; do
    if [ -f "$html" ]; then
        dir=$(dirname "$html")
        app_name=$(basename "$(dirname "$dir")")
        # Skip landing page
        if [ "$app_name" = "landing" ]; then
            echo "  Skipped: landing (not an app)"
            continue
        fi
        add_firebase_sdk "$html"
        create_firebase_js "$dir" "$app_name" "$UTILITIES_CONFIG"
    fi
done

echo ""
echo "=== Setting up Lead Apps (ronnascanner) ==="
for html in /Users/latarencebutts/mdo3d/projects/ronnascanner/*/public/index.html; do
    if [ -f "$html" ]; then
        dir=$(dirname "$html")
        app_name=$(basename "$(dirname "$dir")")
        add_firebase_sdk "$html"
        create_firebase_js "$dir" "$app_name" "$LEADS_CONFIG"
    fi
done

echo ""
echo "=== Done ==="
